#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"


# APLICACIONES QUE SE LANZARÁN AL INICIO EN FLUXBOX

# Desabilito la opción de que se apague la pantalla después de 10 minutos
xset -dpms s off

# Esto lo deja así: Standby: 0    Suspend: 0    Off: 0
# Desabilito esa opción que está por defecto porque en algunos ordenadores
# cuando la pantalla se apaga se cuelga (edemás de que cuando uno está
# viendo películas no conviene que se apague después de 10 min)
# Si usted desea ver el status de xset ponga en la terminal: xset q
# al final debe de decir: DPMS is Disabled

# xsct_gui https://github.com/wachin/xsct_gui
# sleep 20; /home/wachin/Dev-python/xsct_gui/Launcher.sh &

# Internet
nm-applet &

# Habilitar KDE Connect:
kdeconnect-indicator &

# Terminales
konsole &

# Elevación de privilegios  para ciertas aplicaciones como: Synaptic, Discos, etc
/usr/lib/i386-linux-gnu/libexec/polkit-kde-authentication-agent-1 &

# inicie pulseaudio antes de pnmixer
#start-pulseaudio-x11 &
pulseaudio --start &

# Mixer escrito en Qt
pnmixer &

# Para que la tecla numerica funcione
numlockx on &

# MarkdownnEditor
vnote &

# Es nesesario para poder configurar la velocidad de los cursores de dispositivos externos:
xinput-gui &

# Lanzar el Administrador de archivos
# Pueden activar cualquiera de los siguientes si los instalan(exepto thunar que ya está instalado): 
#thunar &
dolphin &
#caja & 
# nemo &
# nautilus &
#pcmanfm &

# Editores de texto, elija cual usar (debe instalarlo):
kate &
#gedit & 
#pluma &
#geany &

# Poner el bloque de notas en la bandeja del sistema:
#feathernotes /home/wachin/Documentos/FeatherNotes/2024-07-15-wachi.fnx &
xfce4-notes &

# Aplicacion para poder expulsar USB, Pendrives


# Iniciar el bus de accesibilidad del usuario, si aún no se está ejecutando
#/usr/libexec/at-spi-bus-launcher --launch-immediately  &

# Colocar en el escritorio el último fondo seleccionado
sleep 10; nitrogen --restore &



# AJUSTE DE DISTRIBUCIÓN DE TECLADO
# Si usted usa un teclado en español con el esquema siguiente: http://kbdlayout.info/kbdsp/overview+names
# le recomiendo que use el siguienta para que coincidan las letras:
setxkbmap -layout es & # Teclado Español europeo

# Si desea otro teclado aquí están (igual si activan alguno deben desactivar el anterior):
#setxkbmap -layout de & # Teclado Alemán
#setxkbmap -layout us & # Teclado Inglés
#setxkbmap -layout latam & # Teclado Español latino
#setxkbmap -layout fr & # Teclado Francés
#setxkbmap -layout gb & # Teclado Inglés británico
#setxkbmap -layout gr & # Teclado Griego
#setxkbmap -layout it & # Teclado Italiano
#setxkbmap -layout pl & # Teclado Polaco
#setxkbmap -layout pt & # Teclado Portugués
#setxkbmap -layout ru & # Teclado Ruso
             
# Esto es necesario apra asegurarse que al inicio se cargue el teclado correcto
# En el sistema operativo los demás idiomas están en /usr/share/X11/xkb/symbols/
# eso es si desea saber cuál es el nombre del archivo, allí usted
# deberá abrir alguno, ejemplo puede abrir: de el cual es el alemán
# algún otro idioma usted debería tener alguna idea de cómo se podría 
# llamar el respectivo archivo

# PROGRAMAS DE USUARIO (OPCIONALES)
# Lo siguiente es para aplicaciones opcionales que quiera algún usuario:

# Para hacer capturas de pantalla
ksnip &

# Solucionar que en Debian 12 no funciona el doble clic del touchpad
# a mi laptop Dell Inspiron 1750

#synclient TapButton1=1
#synclient ClickFinger1=1
#synclient TapButton2=3
#synclient ClickFinger2=3
#synclient TapButton3=2
#synclient ClickFinger3=2


# Navegadores web, elija cual usar:
# firefox-esr &
#firefox &
chromium &


# Alarm Clock Applet
alarm-clock-applet  &

# Si Ud usa una impresora HP deberá de instalar HPLIP instále: sudo apt-get install hplip-gui
# para lanzarlo se puede desde las aplicaciones instaladas 
# o también desde la terminal con: hp-systray -x
# y para que se cargue en la bandeja del sistema active lo siguiente:
#hp-systray -x &

# Si usa Shutter para tomar captura de pantallas, este es el comando 
# para que se cargue iconizado y no ocupe espacio 
#shutter --min_at_startup &

# El siguiente es para activar el monitor debatería, pero no lo active porque no funciona con gammy abierto:
#xfce4-power-manager &

# Poner el portapapeles en la barra de herramientas
# xfce4-clipman &

# Si usted utiliza Dropbox el siguiente comando es para que se abra
#dropbox start -i &

# Si tu laptop u ordenador tiene Bluetooth debe activarlo y si 
#blueman-applet &

# Si uste tuviera un teclado externo Logitech k400 instale: sudo apt install solaar
# busquelo entre sus aplicaciones, yo lo uso para invertir la tecla Fn
# para que se iconize en la bandeja del sistema active:
#solaar &

# SI DESEA AÑADIR UNA APLICACION AL INICIO ASEGÚRESE DE PONER''&'' AL FINAL, EJEMPLO:
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
